version: "3"

networks:
  jenkins:
    external: false

volumes:
  jenkins_home:
    driver: local
  gitea:
    driver: local
  postgres:
    driver: local

services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins
    restart: always
    networks:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
      - "50000:50000"

  git:
    image: gitea/gitea:1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASS}
    restart: always
    networks:
      - jenkins
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2022:22"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - jenkins
    volumes:
      - postgres:/var/lib/postgresql
